name: Deploy to Production 🚀
"on":
  push:
    branches:
      - production
env:
  REACT_APP_ENVIRONMENT: "production"
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_BLACKLIST_LANDING_LIVE }}"
          channelId: live
          projectId: blacklist-landing-live
